node:
  #build: .
  image: vernonco/mariadb-cluster:stable
  container_name: galera_node
  hostname: node
  ports:
    - "3306:3306"
    - "4444:4444"
    - "4567:4567"
    - "4567:4567/udp"
    - "4568:4568"
  environment:
    - TERM=xterm
    - MYSQL_INITDB_SKIP_TZINFO=yes
    - MYSQL_ROOT_PASSWORD=yourrootpassword
  volumes:
    - /var/lib/docker/data:/var/lib/mysql:Z
    - /path_to/certs:/etc/mysql/ssl
    - /path_to/my.cnf:/etc/mysql/my.cnf
  log_opt:
    max-size: "100k"
    max-file: "20"
  restart: always
  command: --log-error=/dev/stderr --log_warnings=3


phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: myadmin
  ports:
    - "80:80"
  links:
    - node:db

# **** used to start nodes with root password  **********
# put local my.cnf on machine with wsrep option for master or nodes
# log opt prevent log files from getting out of hand
# TERM allows nano